### PR TITLE
Added BeelineQueryListenerForJDBC to auto-instrument JDBC

### PR DESCRIPTION
**Pull request by MarsianMan**
This automatically proxies DataSource and adds query listener to Spring. This will use the Beeline to send JDBC traces to Honeycomb.

To disable this behavior, set `honeycomb.beeline.jdbc.enabled=false` in Spring's application properties.

### CODE REVIEW

**Comment by paulosman** [comment]
I'm seeing some orphaned traces when I test this out locally. Specifically, if I have a Spring Boot 2 app with a handler method that performs a database write (via a `CrudRepository`) and then returns a `RedirectView` (not sure if that's relevant), I see multiple traces being generated by the same `POST` request. Here's the method:

```
@PostMapping("/bees/create")
public RedirectView addBees(@ModelAttribute Bee bee, Model model) {
    bees.save(bee);
    model.addAttribute("bees", bees.findAll());
    return new RedirectView("/bees");
}
```

Where `bees` is a `CrudRepository`. Given the above code snippet, I would expect to see a root span generated for the incoming `HTTP` request (the `POST`) with child spans for the SQL statements (because the bees table has an autoincrementing value, there should be a `SELECT` for the next id value and then an `INSERT` for the actual write). Instead, I see two traces:

Screen Shot 2020-06-18 at 9 24 06 AM

Which seems to cover the first part (the `HTTP` request and the first `SELECT`) and then:

Screen Shot 2020-06-18 at 9 24 31 AM

Which seems to cover the second part (the `INSERT` statement). Is it possible we're losing the trace id somewhere?

**Comment by patrickbray** [comment]
@MarsianMan @paulosman this looks great I was just looking at trying to create something similar for our mysql instrumentation based on the brave Zipkin query interceptor as outlined here https://github.com/openzipkin/brave/tree/master/instrumentation/mysql8. 

Let me know if we can help test this out at all? Also wondering if it would be possible to add a config parameter for a pattern of queries to ignore? 

We are using something like this for our current Zipkin implementation to avoid extra unnecessary noise in traces. 

```
private final Pattern exclude = Pattern.compile("(set.+)|(commit)|(select @@session.tx_read_only)", 2);
```

**Comment by MarsianMan** [comment]
@paulosman Whoops! The active span was being closed after the first query, so any subsequent traces were getting orphaned. Now, the active span only get closed when a trace is manually started (i.e. no active span was detected).

I also added BeelineQueryListenerForJDBC as new instrumentation type "spring_jdbc".

**Comment by paulosman** [comment]
> @MarsianMan @paulosman this looks great I was just looking at trying to create something similar for our mysql instrumentation based on the brave Zipkin query interceptor as outlined here https://github.com/openzipkin/brave/tree/master/instrumentation/mysql8.
> 
> Let me know if we can help test this out at all? Also wondering if it would be possible to add a config parameter for a pattern of queries to ignore?
> 
> We are using something like this for our current Zipkin implementation to avoid extra unnecessary noise in traces.
> 
> ```
> private final Pattern exclude = Pattern.compile("(set.+)|(commit)|(select @@session.tx_read_only)", 2);
> ```
> 
> Not sure if this would be necessary with the proxy based approach though?

Thank you for the suggestion! In the interest of keeping things simple, let's safe it for now... if it starts to become a problem (noisy traces), we can look at adding it in a future release. 

As mentioned, testing help would be greatly appreciated! Thank you!

**Comment by patrickbray** [comment]
I did an initial test of this against a sample application I am using & looks great so far. Will get this deployed in our dev environment on Monday for better soak test as this will be super helpful for us.

**Pull request merged**
